server:
  port: 5000

spring:
  cloud:
    gateway:
      routes:
        - id: exercise-result-service
          uri: http://exercise-result:5000
          predicates:
            - Path=/api/exercise/*/result/**

        - id: exercise-service
          uri: http://exercise:5000
          predicates:
            - Path=/api/exercise/**
