server:
  port: 5002

spring:
  cloud:
    gateway:
      routes:
        - id: exercise-result-service
          uri: http://localhost:5001
          predicates:
            - Path=/api/exercise/*/result/**

        - id: exercise-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/exercise/**
