server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_BRANCH:main}
          search-paths: config-repo/config